export const navitem = [
  "Stock Video",
  "Video Templates",
  "Music",
  "Sound Effects",
  "Graphic Templates",
  "Graphics",
  "Presentation Templates",
  "Photos",
  "Fonts",
  "Add-ons",
  "More",
];

export const navitems2 = [
  "Stock Video",
  "Video Templates",
  "Music",
  "Sound Effects",
  "Graphic Templates",
  "Graphics",
  "Fonts",
  "Add-ons",
  "More",
];

export const dropdownContents = [
  ["Stock Footage", "Motion Graphics", "All Stock Video"],
  [
    "After Effect",
    "Premiere Pro",
    "Apple Motion",
    "Final Cut Pro",
    "DaVinci Resolve",
    "All Video Templates",
  ],
  ["Royality Free Music", "logos & Idents", "All Music"],
  [
    "Game Sounds",
    "Tranisition & Movement",
    "Interface Sounds",
    "Human Sounds",
    "Urban Sounds",
    "Nature Sounds",
    "Foley Sounds",
    "Domestic Sounds",
    "Voice Sounds",
    "All Sound Effects",
  ],
  [
    "Adobe Photoshop",
    "Adobe Illustrator",
    "Adobe InDesign",
    "Sketch",
    "Adobe XD",
    "Affinity Designer",
    "GIMP",
    "CorelDRAW",
    "All Graphic Templates",
  ],
  [
    "Backgrounds",
    "Textures",
    "Illustrations",
    "Patterns",
    "Objects",
    "Decoration",
    "Illustrations",
    "All Graphics",
  ],
  ["Keynotes", "Google Slides", "PowerPoint", "All Presentation Templates"],
  [],
  ["serif", "sans-serif", "Script & Handwritten", "All Fonts"],
  [
    "Actions & Presets",
    "Brushes",
    "Layer Styles",
    "Palettes",
    "Plug-ins",
    "All Add-ons",
  ],
  [],
];

export const doropdownContent2 = [
  ["Stock Footage", "Motion Graphics", "All Stock Video"],
  [
    "After Effect",
    "Premiere Pro",
    "Apple Motion",
    "Final Cut Pro",
    "DaVinci Resolve",
    "All Video Templates",
  ],
  ["Royality Free Music", "logos & Idents", "All Music"],
  [
    "Game Sounds",
    "Tranisition & Movement",
    "Interface Sounds",
    "Human Sounds",
    "Urban Sounds",
    "Nature Sounds",
    "Foley Sounds",
    "Domestic Sounds",
    "Voice Sounds",
    "All Sound Effects",
  ],
  [
    "Adobe Photoshop",
    "Adobe Illustrator",
    "Adobe InDesign",
    "Sketch",
    "Adobe XD",
    "Affinity Designer",
    "GIMP",
    "CorelDRAW",
    "All Graphic Templates",
  ],
  [
    "Backgrounds",
    "Textures",
    "Illustrations",
    "Patterns",
    "Objects",
    "Decoration",
    "Illustrations",
    "All Graphics",
  ],
  ["Keynotes", "Google Slides", "PowerPoint", "All Presentation Templates"],
  [
    "Actions & Presets",
    "Brushes",
    "Layer Styles",
    "Palettes",
    "Plug-ins",
    "All Add-ons",
  ],
  [],
];

export const moreData = [
  {
    title: "CMS Templates",
    sub_items1: [
      "Dropal",
      "Joomla",
      "Magento",
      "Muse",
      "OpenCart",
      "prestaShop",
    ],
    sub_items2: ["Shopify", "Unbounce", "Ghost", "Tumblr"],
    ending: "All CSS Templates",
  },
  {
    title: "WordPress",
    sub_items1: ["Themes", "Plugins", "Template Kits"],
    ending: "All WordPress",
  },
  {
    title: "3D",
    ending: "All 3D",
  },
  {
    title: "Free Files",
    ending: "Monthly Free Files",
  },
];
